### PR TITLE
distributed v2021.1.1

### PR DESCRIPTION
**Pull request by jrbourbeau**
This PR bumps the distributed version to the 2021.1.1 release

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes https://github.com/conda-forge/distributed-feedstock/pull/159

### CODE REVIEW

**Comment by jakirkham** [comment]
Weird Azure doesn't appear to be running.

**Comment by jrbourbeau** [comment]
Hrm, that seemed to do the trick

**Comment by jakirkham** [comment]
One of the Travis CI jobs had an HTTP error downloading some Conda packages. Restarted it

**Comment by jakirkham** [comment]
Looks like the bot added PR ( https://github.com/conda-forge/distributed-feedstock/pull/159 ) to update. Just added a note in the OP of this PR to close that PR when this one is merged, which the bot will treat as completed. Hope that is ok 🙂

**Comment by jakirkham** [comment]
Thanks James! 😄

**Pull request merged**
