### PR TITLE
bump version to 1.21.0

### PR DESCRIPTION
**Pull request by mrocklin**
Also remove @koverholt from maintainers

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @koverholt do you consent to being removed from the maintainers of the `distributed` package on conda-forge?  I'm just doing some cleaning here.  I appreciate you getting us up and running on this service.

**Comment by mrocklin** [comment]
Should I be concerned that Appveyor isn't coming up?

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by mrocklin** [comment]
Ah ha!  There we go.  Thanks for the push @jakirkham !

**Comment by koverholt** [comment]
> cc @koverholt do you consent to being removed from the maintainers of the distributed package on conda-forge? I'm just doing some cleaning here. I appreciate you getting us up and running on this service.

Works for me, thanks for checking!

**Comment by mrocklin** [comment]
Thanks all!  Merging.

**Comment by jakirkham** [comment]
np.

With as much content and activity as conda-forge has, we periodically run into rate limits of APIs (particularly GitHub’s). Expect that is why AppVeyor didn’t show up (have seen it before).

Independently there were some bug fixes needed in the AppVeyor config.

**Pull request merged**
