### PR TITLE
Release 2021.06.2

### PR DESCRIPTION
**Pull request by jrbourbeau**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jrbourbeau** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
FWIW I think we can go back to relying on the bot to generate these if it makes it easier. Was just really eager to get the last May release out 😂

**Comment by jrbourbeau** [comment]
Sure, I'm fine either way. It seemed like the bots were taking a while the past couple of releases, so I just started pushing up PRs myself. 

The Drone CI build seems to be taking a while. Do you know if there's just a large backlog or if there are other issues?

**Comment by jakirkham** [comment]
Yeah they operate on a cron job. So it depends on when they last ran and when the package was added to PyPI. Should add the check solvable feature ( https://github.com/conda-forge/distributed-feedstock/pull/154 ) makes it take a bit longer since it will skip making a PR until the dependencies are available (in our case `dask-core`)

Am not sure. Will ask. Though we do have fewer resources there as compared to other CIs. So it may not be too surprising that it takes a bit

**Pull request merged**
