### PR TITLE
Pin message-pack to <1.0 (recently release and incompatible)

### PR DESCRIPTION
**Pull request by Carreau**
As per dask/distributed#3494,  dask/distributed#3498 and dask/distributed#3491

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* ~~[ ] Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
Thanks @Carreau! 😄

If we wind up needing to mark packages as `broken`, we can now do so by [submitting the package names here]( https://github.com/conda-forge/cf-mark-broken ).

**Comment by jjhelmus** [comment]
Alternatively the existing packages can be [hotfixed](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock) to include a maximum message-pack pinning.  

If the older packages are moved to `broken` please ping me so I can adjust the packages in `defaults` accordingly.

**Comment by jjhelmus** [comment]
A hotfix for older versions of distributed is being worked on in conda-forge/conda-forge-repodata-patches-feedstock#32

**Comment by Carreau** [comment]
Thanks, I was unsure I understood how to hotfix. 

I dropped a question in the PR you link, in particular I'm not quite sure I understand how this gen-patch-json will only apply the hotfix to already released packages.

**Pull request merged**
