### PR TITLE
Release 2024.10.0

### PR DESCRIPTION
**Pull request by pentschev**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pentschev** [comment]
@conda-forge-admin, please rerender

**Comment by charlesbluca** [comment]
Think we'll need to do something like https://github.com/dask/distributed/pull/8890 here to address the [sunsetting of implicit `pip` build deps](https://conda-forge.org/news/2024/08/21/sunsetting-pip-deps/)

**Comment by pentschev** [comment]
Just noticed that as well, for now I've simply added `setuptools` without a pin, like in the [dask-core recipe](https://github.com/conda-forge/dask-core-feedstock/blob/main/recipe/meta.yaml#L23).

**Comment by pentschev** [comment]
@conda-forge-admin, please rerender

**Comment by charlesbluca** [comment]
Think that should do it, though was going to comment on the dask-core feedstock release saying for posterity it might make sense using `setuptools >=62.6` since this is the pinning specified in each project's [pyproject.toml](https://github.com/dask/distributed/blob/main/pyproject.toml#L2)

**Comment by pentschev** [comment]
Ok, no need to wait here then, pinned added in https://github.com/conda-forge/distributed-feedstock/pull/294/commits/1a262cea8f33f0e4d278352be95e9ec647daaf70 .

**Comment by pentschev** [comment]
@conda-forge-admin, please rerender

**Review by charlesbluca — APPROVED** [review]
Thanks @pentschev! Tried generating the recipe with `grayskull pypi distributed` just to make sure we weren't missing any other dependency changes, this looks good

**Pull request merged**
