### PR TITLE
remove dask-mpi from entry points

### PR DESCRIPTION
**Pull request by mrocklin**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mrocklin** [comment]
In service of https://github.com/conda-forge/dask-mpi-feedstock/pull/6

**Comment by jakirkham** [comment]
Should we pull build number 0 of this package (given it still has the entrypoint)?

**Comment by mrocklin** [comment]
I don't think it's high priority.

**Comment by mrocklin** [comment]
Or rather, I doubt that having the old build around will affect many people.

**Pull request merged**
