### PR TITLE
Bump version to 2.0.0

### PR DESCRIPTION
**Pull request by mrocklin**
Also add noarch now that we can drop the Python 2 conditions

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mrocklin** [comment]
@conda-forge-admin, please rerender

**Comment by mrocklin** [comment]
Woot.  Down to noarch here as well now.

cc @jakirkham .  I think I've done everything correctly here, but wouldn't pass up a quick check from you :)

**Comment by mrocklin** [comment]
Failed due to dask-core not being out yet.  Am I able to retry things manually without having Azure Pipelines access?

**Comment by jakirkham** [comment]
LGTM.

Likely `dask-core` is out. We are just waiting for it to show up on the CDN. Takes some time to mirror across ~30mins.

Unfortunately not. We've asked our contacts at Microsoft to support GitHub logins on Azure. Sounds like this is pretty high priority for them. However it hasn't happened yet.

Will restart and see if that clears things up. 🙂

**Comment by jakirkham** [comment]
Thanks @mrocklin! 😄

**Pull request merged**
