### PR TITLE
bump version to 1.16.1

### PR DESCRIPTION
**Pull request by mrocklin**
Also list jcrist and martindurant as maintainers

@jcrist and @martindurant do you consent to being listed as maintainers of the dask/distributed feedstock?

### CODE REVIEW

**Comment by mrocklin** [comment]
Hrm, something is up with Appveyor builds.  Does anyone know if there is anything I can do to resolve this?

**Comment by jakirkham** [comment]
It's a known issue ( https://github.com/conda-forge/conda-forge.github.io/issues/357 ). We have proposed fixes that are in discussion.

If you are feeling brave/wanting to see something ASAP, you could try re-rendering with a patched/dev version of `conda-smithy` using PR ( https://github.com/conda-forge/conda-smithy/pull/489 ). Though this isn't merged yet, I expect it will be soon and can be release soon after.

**Comment by mrocklin** [comment]
Do you have a rough estimate on "soon"?  Sometime between a day and a week?  I'm happy to let this lie for a day or two.

**Comment by jakirkham** [comment]
I would hope in the next day or two. FWIW that fix works and is tested. ( https://github.com/conda-forge/setuptools-feedstock/pull/62 ). It is more about getting consensus at this point.

Side note: Probably could just copy the line from that example PR to resolve this more easily.

**Comment by jcrist** [comment]
Fine by me.

**Pull request merged**
