### PR TITLE
Remove new style CLI from `entry_points` section

### PR DESCRIPTION
**Pull request by jrbourbeau**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Maybe this fixes the issue discussed https://github.com/conda-forge/distributed-feedstock/pull/225#discussion_r1000211836. cc @jakirkham

### CODE REVIEW

**Comment by jrbourbeau** [comment]
Note that I'm intentionally keeping the `dask scheduler --help`, etc. tests

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
As noted in the thread ( https://github.com/conda-forge/distributed-feedstock/pull/225#discussion_r1000935925 ), think we want to remove [the entry point from `dask`]( https://github.com/conda-forge/dask-feedstock/blob/c7a89482d2061652afb380f14d4df25037e0c9b1/recipe/meta.yaml#L15-L16 ) too

**Comment by jrbourbeau** [comment]
Thanks @jakirkham! I've built / installed this PR locally on my mac and, with the changes here, I'm able to run `dask scheduler` and things work 🎉.

That said, I'm no longer sure why this is working since, IIUC, we're relying on the `dask` entrypoint to be defined in the `dask` conda package, but `distributed` doesn't install `dask` as it only depends on `dask-core`. 

Some more context, in the past (xref https://github.com/conda-forge/coiled-feedstock/pull/89#issuecomment-1103161756) I've seen Windows-only issues with entrypoints of `conda` packages, but not when installed with `pip`. Since I'm on a mac, I've never been able to reproduce these issues locally, but have seen that following fixes like https://github.com/conda-forge/distributed-feedstock/pull/225, things are fixed on Windows. 

I think we should try:

1. Add the `dask` entypoint that currently lives in the `dask` conda package to `dask-core`.
2. Remove the `dask` entrypoint from the `dask` conda package.
3. Merge this PR which removes entrypoints altogether from the `distributed` recipe (but keep a few related tests) 

@jakirkham does this sound reasonable to you?

**Comment by jrbourbeau** [comment]
Cool. Yeah, I'll push up some PRs now

**Comment by jakirkham** [comment]
Thanks James! 🙏 

Those are all in now. Just need to wait for packages to upload and then test them out 🙂

**Comment by jakirkham** [comment]
So I tried the new binaries, but it looks like the `dask` CLI still doesn't work.

```sh
$ dask --help
Usage: dask [OPTIONS] COMMAND [ARGS]...

  Dask command line interface.

Options:
  --version   Show the version and exit.
  -h, --help  Show this message and exit.

Commands:
  docs  Open Dask documentation (https://docs.dask.org/) in a web browser.
  info  Information about your dask installation.
```

```sh
$ dask scheduler --help
Usage: dask [OPTIONS] COMMAND [ARGS]...
Try 'dask -h' for help.

Error: No such command 'scheduler'.
```

**Comment by jakirkham** [comment]
Proposing we drop the `dask` entry point ( https://github.com/conda-forge/dask-core-feedstock/pull/144 )

**Pull request merged**
