### PR TITLE
Use click pre-8 for releases prior to 2021.5.0

### PR DESCRIPTION
**Pull request by jakirkham**
Click 8 recently made a change that broke `distributed`. This has been fixed upstream ( https://github.com/dask/distributed/pull/4810 ) and will be in the next release. Unfortunately older releases remain broken. This fixes the version constraint for older releases.

cc @jrbourbeau

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by jrbourbeau — APPROVED** [review]
Thanks for fixing @jakirkham! This LGTM

**Comment by jrbourbeau** [comment]
I'm going to merge this in an then try installing `distributed` to make sure we pull in `click<8`

**Comment by jakirkham** [comment]
I think we still need the repodata patch for things to work

**Comment by jrbourbeau** [comment]
Gotcha. My understanding is the patch here would work for the latest `distributed=2021.4.1` and the repodata patch will take care of all the older releases. Either way, feel free to merge the repodata patch when you think it's good to go (I don't have push access to ` conda-forge/conda-forge-repodata-patches-feedstock`)

**Comment by jakirkham** [comment]
Unfortunately Conda has historically had behavior that sometimes leads to using older versions that are less constrained. If one forces this version, then yes it should work. However if one doesn't specify the version, it probably won't.

**Comment by jakirkham** [comment]
Think everything is mirrored to CDN. So would give it a try now to see if that fixes the packages. If not, happy to take another look 🙂

**Comment by jrbourbeau** [comment]
Locally trying to install `distributed` still pulls in `click=8` though it's also using the older build (build 0) for `distributed`

<details>
<summary>Details:</summary>

```
(base) ➜  ~ conda create -n test python=3.9 distributed
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.10.1

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /Users/james/miniforge3/envs/test

  added / updated specs:
    - distributed
    - python=3.9


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    click-8.0.0                |   py39h6e9494a_0         145 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         145 KB

The following NEW packages will be INSTALLED:

  ca-certificates    conda-forge/osx-64::ca-certificates-2020.12.5-h033912b_0
  certifi            conda-forge/osx-64::certifi-2020.12.5-py39h6e9494a_1
  click              conda-forge/osx-64::click-8.0.0-py39h6e9494a_0
  cloudpickle        conda-forge/noarch::cloudpickle-1.6.0-py_0
  cytoolz            conda-forge/osx-64::cytoolz-0.11.0-py39hcbf5805_3
  dask-core          conda-forge/noarch::dask-core-2021.4.1-pyhd8ed1ab_0
  distributed        conda-forge/osx-64::distributed-2021.4.1-py39h6e9494a_0
  fsspec             conda-forge/noarch::fsspec-2021.4.0-pyhd8ed1ab_0
  heapdict           conda-forge/noarch::heapdict-1.0.1-py_0
  libcxx             conda-forge/osx-64::libcxx-11.1.0-habf9029_0
  libffi             conda-forge/osx-64::libffi-3.3-h046ec9c_2
  locket             conda-forge/noarch::locket-0.2.0-py_2
  msgpack-python     conda-forge/osx-64::msgpack-python-1.0.2-py39hedf5dff_1
  ncurses            conda-forge/osx-64::ncurses-6.2-h2e338ed_4
  openssl            conda-forge/osx-64::openssl-1.1.1k-h0d85af4_0
  partd              conda-forge/noarch::partd-1.2.0-pyhd8ed1ab_0
  pip                conda-forge/noarch::pip-21.1.1-pyhd8ed1ab_0
  psutil             conda-forge/osx-64::psutil-5.8.0-py39h89e85a6_1
  python             conda-forge/osx-64::python-3.9.4-h9133fd0_0_cpython
  python_abi         conda-forge/osx-64::python_abi-3.9-1_cp39
  pyyaml             conda-forge/osx-64::pyyaml-5.4.1-py39hcbf5805_0
  readline           conda-forge/osx-64::readline-8.1-h05e3726_0
  setuptools         conda-forge/osx-64::setuptools-49.6.0-py39h6e9494a_3
  sortedcontainers   conda-forge/noarch::sortedcontainers-2.3.0-pyhd8ed1ab_0
  sqlite             conda-forge/osx-64::sqlite-3.35.5-h44b9ce1_0
  tblib              conda-forge/noarch::tblib-1.7.0-pyhd8ed1ab_0
  tk                 conda-forge/osx-64::tk-8.6.10-h0419947_1
  toolz              conda-forge/noarch::toolz-0.11.1-py_0
  tornado            conda-forge/osx-64::tornado-6.1-py39hcbf5805_1
  tzdata             conda-forge/noarch::tzdata-2021a-he74cb21_0
  wheel              conda-forge/noarch::wheel-0.36.2-pyhd3deb0d_0
  xz                 conda-forge/osx-64::xz-5.2.5-haf1e3a3_1
  yaml               conda-forge/osx-64::yaml-0.2.5-haf1e3a3_0
  zict               conda-forge/noarch::zict-2.0.0-py_0
  zlib               conda-forge/osx-64::zlib-1.2.11-h7795811_1010


Proceed ([y]/n)? n


CondaSystemExit: Exiting.
```

</details>

**Comment by jakirkham** [comment]
Hmm...maybe I was a few minutes early in saying things should work? Tried locally and am seeing the following now:

<details>

```
$ conda create -n test python=3.9 distributed
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/jkirkham/miniconda/envs/test

  added / updated specs:
    - distributed
    - python=3.9


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cytoolz-0.11.0             |   py39hcbf5805_3         342 KB  conda-forge
    distributed-2021.4.1       |   py39h6e9494a_1         1.1 MB  conda-forge
    msgpack-python-1.0.2       |   py39hedf5dff_1          82 KB  conda-forge
    pip-21.1.1                 |     pyhd8ed1ab_0         1.1 MB  conda-forge
    psutil-5.8.0               |   py39h89e85a6_1         350 KB  conda-forge
    python-3.9.4               |h9133fd0_0_cpython        12.6 MB  conda-forge
    tornado-6.1                |   py39hcbf5805_1         646 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        16.2 MB

The following NEW packages will be INSTALLED:

  ca-certificates    conda-forge/osx-64::ca-certificates-2020.12.5-h033912b_0
  certifi            conda-forge/osx-64::certifi-2020.12.5-py39h6e9494a_1
  click              conda-forge/noarch::click-7.1.2-pyh9f0ad1d_0
  cloudpickle        conda-forge/noarch::cloudpickle-1.6.0-py_0
  cytoolz            conda-forge/osx-64::cytoolz-0.11.0-py39hcbf5805_3
  dask-core          conda-forge/noarch::dask-core-2021.4.1-pyhd8ed1ab_0
  distributed        conda-forge/osx-64::distributed-2021.4.1-py39h6e9494a_1
  fsspec             conda-forge/noarch::fsspec-2021.4.0-pyhd8ed1ab_0
  heapdict           conda-forge/noarch::heapdict-1.0.1-py_0
  libcxx             conda-forge/osx-64::libcxx-11.1.0-habf9029_0
  libffi             conda-forge/osx-64::libffi-3.3-h046ec9c_2
  locket             conda-forge/noarch::locket-0.2.0-py_2
  msgpack-python     conda-forge/osx-64::msgpack-python-1.0.2-py39hedf5dff_1
  ncurses            conda-forge/osx-64::ncurses-6.2-h2e338ed_4
  openssl            conda-forge/osx-64::openssl-1.1.1k-h0d85af4_0
  partd              conda-forge/noarch::partd-1.2.0-pyhd8ed1ab_0
  pip                conda-forge/noarch::pip-21.1.1-pyhd8ed1ab_0
  psutil             conda-forge/osx-64::psutil-5.8.0-py39h89e85a6_1
  python             conda-forge/osx-64::python-3.9.4-h9133fd0_0_cpython
  python_abi         conda-forge/osx-64::python_abi-3.9-1_cp39
  pyyaml             conda-forge/osx-64::pyyaml-5.4.1-py39hcbf5805_0
  readline           conda-forge/osx-64::readline-8.1-h05e3726_0
  setuptools         conda-forge/osx-64::setuptools-49.6.0-py39h6e9494a_3
  sortedcontainers   conda-forge/noarch::sortedcontainers-2.3.0-pyhd8ed1ab_0
  sqlite             conda-forge/osx-64::sqlite-3.35.5-h44b9ce1_0
  tblib              conda-forge/noarch::tblib-1.7.0-pyhd8ed1ab_0
  tk                 conda-forge/osx-64::tk-8.6.10-h0419947_1
  toolz              conda-forge/noarch::toolz-0.11.1-py_0
  tornado            conda-forge/osx-64::tornado-6.1-py39hcbf5805_1
  tzdata             conda-forge/noarch::tzdata-2021a-he74cb21_0
  wheel              conda-forge/noarch::wheel-0.36.2-pyhd3deb0d_0
  xz                 conda-forge/osx-64::xz-5.2.5-haf1e3a3_1
  yaml               conda-forge/osx-64::yaml-0.2.5-haf1e3a3_0
  zict               conda-forge/noarch::zict-2.0.0-py_0
  zlib               conda-forge/osx-64::zlib-1.2.11-h7795811_1010


Proceed ([y]/n)? 
```

</details>

**Comment by jrbourbeau** [comment]
Yep, it looks like things are available now! The following all pull in `click=7.1.2` for me locally:

- `conda create -n test python=3.9 distributed`
- `conda create -n test python=3.9 dask`
- `conda create -n test python=3.9 dask=2.30.0`

**Comment by jakirkham** [comment]
Great, thanks James! 😄

**Comment by jakirkham** [comment]
Filed issue ( https://github.com/conda-forge/distributed-feedstock/issues/166 ) to remind us to remove this constraint in the upcoming release

**Pull request merged**
