### PR TITLE
MNT: rerender

### LINKED ISSUE #52: @conda-forge-admin, please re-render
@conda-forge-admin, please re-render.

Note: Needed for `conda-build` 3 support.

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #52.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #52

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please lint.

**Comment by jakirkham** [comment]
Oops, forgot to merge this. Feel free to merge or close, @mrocklin. :)

**Comment by mrocklin** [comment]
Ah, I did see those pass through my e-mail but didn't check them.

I'm inclined to merge the other one, just because it will avoid the need to
run tests again

**Comment by jakirkham** [comment]
Addressed in PR ( https://github.com/conda-forge/distributed-feedstock/pull/54 ).

**Pull request closed without merging**
