### PR TITLE
bump version to 1.17.0

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Comment by jjhelmus** [comment]
Should the `sortedcontainers` requirement be changed to `sortedcollections`?

**Comment by mrocklin** [comment]
I think that we now only depend on `sortedcontainers`.  The entry in requirements.txt is probably old from when we used to depend on both (`sortedcollections` depends on `sortedcontainers`),

**Comment by jakirkham** [comment]
Seems right. All I can find of either is this [line]( https://github.com/dask/distributed/blob/1.17.0/distributed/scheduler.py#L13 ) importing `sortedcontainers`.

**Comment by mrocklin** [comment]
Hrm, I got the following error in an e-mail from Circle-CI :+1: 

```
# $ conda config --set anaconda_upload yes

anaconda_upload is not set.  Not uploading wheels: []
Using Anaconda API: https://api.anaconda.org
Fetching package metadata ....Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 277, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1335, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/opt/conda/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1166, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/urllib3/response.py", line 302, in _error_catcher
    yield
  File "/opt/conda/lib/python3.5/site-packages/urllib3/response.py", line 597, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/opt/conda/lib/python3.5/site-packages/urllib3/response.py", line 562, in _handle_chunk
    returned_chunk = self._fp._safe_read(self.chunk_left)
  File "/opt/conda/lib/python3.5/http/client.py", line 607, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/opt/conda/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
  File "/opt/conda/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 282, in recv_into
    raise SocketError(str(e))
OSError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/requests/models.py", line 739, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/opt/conda/lib/python3.5/site-packages/urllib3/response.py", line 432, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/opt/conda/lib/python3.5/site-packages/urllib3/response.py", line 622, in read_chunked
    self._original_response.close()
  File "/opt/conda/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/lib/python3.5/site-packages/urllib3/response.py", line 320, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: OSError("(104, \'ECONNRESET\')",)', OSError("(104, 'ECONNRESET')",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/upload_or_check_non_existence", line 140, in <module>
    main()
  File "/opt/conda/bin/upload_or_check_non_existence", line 122, in main
    on_channel = distribution_exists_on_channel(cli, meta, owner, channel)
  File "/opt/conda/bin/upload_or_check_non_existence", line 78, in distribution_exists_on_channel
    prepend=False, use_cache=False)
  File "/opt/conda/lib/python3.5/site-packages/conda/api.py", line 24, in get_index
    index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
  File "/opt/conda/lib/python3.5/site-packages/conda/fetch.py", line 300, in fetch_index
    repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
  File "/opt/conda/lib/python3.5/site-packages/conda/fetch.py", line 300, in <listcomp>
    repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
  File "/opt/conda/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.5/site-packages/conda/fetch.py", line 75, in func
    res = f(*args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/conda/fetch.py", line 117, in fetch_repodata
    timeout=(6.1, 60))
  File "/opt/conda/lib/python3.5/site-packages/requests/sessions.py", line 526, in get
    return self.request('GET', url, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/lib/python3.5/site-packages/requests/sessions.py", line 663, in send
    r.content
  File "/opt/conda/lib/python3.5/site-packages/requests/models.py", line 817, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/opt/conda/lib/python3.5/site-packages/requests/models.py", line 742, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: OSError("(104, \'ECONNRESET\')",)', OSError("(104, 'ECONNRESET')",))

./ci_support/run_docker_build.sh returned exit code 1
```

**Comment by jakirkham** [comment]
Sometimes there are network connection errors. Fortunately they are usually transient. Would recommend restarting the build. If the error persists, let us know.

**Pull request merged**
